.TH POIX-CLI "1" "June 2016" "poix-cli 0.12"
.SH NAME
poix-cli \- a remote procedure call client for Poix Core. 
.SH SYNOPSIS
poix-cli [options] <command> [params] \- Send command to Poix Core. 
.TP
poix-cli [options] help \- Asks Poix Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the poix-cli program. poix-cli is an RPC client used to send commands to Poix Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBpoixd\fP, \fBpoix.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
